from .auth_view import register, login_user, user_logout
from .index import index
from .brand_list_view import brand_list
from .brand_add_view import add_brand
from .brand_edit_view import edit_brand
from .bike_model_add_view import add_bike_model
from .bike_model_edit_view import edit_bike_model
from .bike_list_view import bike_list
from .bike_add_view import add_bike
from .bike_detail_view import bike_detail
from .bike_edit_view import edit_bike
from .part_list_view import part_list
from .part_add_view import add_part
from .load_model_view import load_models
from .part_edit_view import edit_part
from .part_detail_view import part_detail
from .part_remove_from_bike_view import remove_part_from_bike
from .bike_sell_view import sell_bike
from .bike_list_for_sale_view import list_bike_for_sale
from .labor_list_view import labor_list
from .labor_add_view import add_labor
from .parttype_list_view import parttype_list
from .dashboard_view import BikeChartView
from .part_search_view import part_search
from .todo_add_view import add_todo
from .todo_edit_view import edit_todo
